name: WSL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  RedHat:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Pull
        run: docker pull redhat/ubi8:latest

      - name: Docker Run
        run: docker run --name redhat redhat/ubi8:latest
        
      - name: Docker Export
        run: |
          docker export -o redhat.tar redhat
        
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN}}
          file: redhat.tar
          tag: redhat
          overwrite: true

