name: repos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

jobs:
  RedHat:
    runs-on: ubuntu-latest

    steps:
      - name: Initial Environment
        run: |
          docker rmi $(docker images -q)
          sudo apt remove --purge apache* mono* nginx* powershell go* nodejs* pypy* python* ruby* sqlcmd* mysql* postgresql* *sqlite* mongodb* dotnet* aspnetcore*
          sudo apt autoremove
          sudo rm -rf /usr/local/lib/android/ /etc/apache2/ /etc/default/mono-xsp4 /etc/nginx/ /opt/hostedtoolcache/ /usr/local/share/chrom* /usr/local/share/edge_driver /usr/local/share/gecko_driver /usr/share/java/selenium-server.jar /usr/local/share/powershell/ /usr/local/share/vcpkg /usr/share/miniconda /home/linuxbrew
          sudo rm -rf $JAVA_HOME_8_X64 $JAVA_HOME_17_X64 $GRAALVM_11_ROOT
          sudo rm -rf /usr/share/dotnet/ /usr/share/php* /opt/az
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Initial Docker File
        run: |
          sed -i '5s/RE_ORG/${{ secrets.ORG }}/g' Dockerfile
          sed -i '5s/RE_ACTIVATIONKEY/${{ secrets.ACTIVATIONKEY }}/g' Dockerfile
          sed -i '16s/RE_PASSWORD/${{ secrets.PASSOWRD }}/g' Dockerfile

      - name: Build Docker
        run: |
          docker build -f Dockerfile -t redhat .
          docker run -d --name redhat redhat
          
      - name: Organize files
        run: |
          docker mv redhat:/repos.tar.gz .
        
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN}}
          file: repos.tar.gz
          tag: redhat
          overwrite: true
